Fix for shortname split (pipe needs to be escaped) + test.
celogeek/MooX-Options pull request #67
Opened 2017-08-21 14:12 UTC by burak

The demonstration of the bug:

    :~ bgursoy$ perl -V:version
    version='5.26.0';

    :~ bgursoy$ perl -MO=Deparse -e 'split "|"'
    split(/|/, $_, 0);
    -e syntax OK

    :~ bgursoy$ perl -MO=Deparse -e 'split "\|"'
    split(/|/, $_, 0);
    -e syntax OK

    :~ bgursoy$ perl -MO=Deparse -e 'split /\|/'
    split(/\|/, $_, 0);
    -e syntax OK

    :~ bgursoy$ perl -MO=Deparse -e 'split /[|]/'
    split(/[|]/, $_, 0);
    -e syntax OK

    :~ bgursoy$ perl -E 'say for split "|", q{foo|bar}'
    f
    o
    o
    |
    b
    a
    r

    :~ bgursoy$ perl -E 'say for split "\|", q{foo|bar}'
    f
    o
    o
    |
    b
    a
    r

    :~ bgursoy$ perl -E 'say for split /\|/, q{foo|bar}'
    foo
    bar

    :~ bgursoy$ perl -E 'say for split /[|]/, q{foo|bar}'
    foo
    bar

2017-08-21 16:39 UTC, rehsack commented on t/11-moo.t
> -    use Moose;
Separate PR, please.

2017-08-21 16:41 UTC, rehsack commented
When you're ready, please squash your commits appropriately.

2017-08-21 16:43 UTC, rehsack requested changes
Please use reasonable commit messages - do not mix examples, comments and explanations.

http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines provides reasonable guidance to do so.

2017-08-22 15:37 UTC, rehsack commented
I cherry-picked the reported issues but refused the patches.

2017-08-22 15:37 UTC, closed without merging

2017-08-22 21:57 UTC, burak commented
Cool.  Sorry I couldn't look at your requests.

2017-08-23 09:41 UTC, rehsack commented
No worries as long as you're happy to receive "only" issuer credits ;)

2017-08-23 10:49 UTC, burak commented
That's fine :) I'm only interested in fixes going live :)